AllCops:
  NewCops: enable
  TargetRubyVersion: 2.0
  SuggestExtensions: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'test/test_ccm.rb'

Metrics/ClassLength:
  Exclude:
   - 'test/test_ccm.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/test_ccm.rb'
